"""Target configuration management.

Targets describe *execution environments* as a set of orthogonal
``options`` (``qos``, ``constraint``, ``time_limit``, ``account``,
``partition``) that agents and users can override per run via ``lc run
--<option> <value>``.  This module owns the target YAML schema, on-load
migration from older formats, option resolution, and the cluster-cache
layer used for scheduler-specific limit checking.
"""
from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

#: User-facing axes exposed as ``--<axis>`` flags on ``lc run``.
OPTION_AXES: tuple[str, ...] = (
    "qos", "constraint", "time_limit", "account", "partition",
)

#: Axes that are only meaningful for scheduler-backed targets.
_SCHEDULER_AXES = frozenset({"qos", "constraint", "partition"})


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


def get_targets_dir() -> Path:
    """Return the user-level targets directory (``~/.lightcone/targets/``)."""
    return Path.home() / ".lightcone" / "targets"


def get_cache_dir() -> Path:
    """Return the cluster cache directory (``~/.lightcone/cache/``)."""
    cache = Path.home() / ".lightcone" / "cache"
    cache.mkdir(parents=True, exist_ok=True)
    return cache


def get_config_path() -> Path:
    """Return the user-level config file path (``~/.lightcone/config.yaml``)."""
    return Path.home() / ".lightcone" / "config.yaml"


# ---------------------------------------------------------------------------
# Target CRUD
# ---------------------------------------------------------------------------


def list_targets() -> list[str]:
    """Return names of saved target configurations."""
    targets_dir = get_targets_dir()
    if not targets_dir.exists():
        return []
    return sorted(p.stem for p in targets_dir.glob("*.yaml"))


def load_target(name: str) -> dict[str, Any] | None:
    """Load a target configuration by name.

    Returns ``None`` if the target does not exist.
    """
    config_path = get_targets_dir() / f"{name}.yaml"
    if not config_path.exists():
        return None
    with open(config_path) as f:
        return yaml.safe_load(f) or {}


def save_target(name: str, config: dict[str, Any]) -> Path:
    """Save a target configuration to ``~/.lightcone/targets/{name}.yaml``."""
    targets_dir = get_targets_dir()
    targets_dir.mkdir(parents=True, exist_ok=True)
    config_path = targets_dir / f"{name}.yaml"
    with open(config_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    return config_path


# ---------------------------------------------------------------------------
# User config
# ---------------------------------------------------------------------------


def load_user_config() -> dict[str, Any]:
    """Load the user-level lightcone-cli configuration."""
    config_path = get_config_path()
    if not config_path.exists():
        return {}
    with open(config_path) as f:
        return yaml.safe_load(f) or {}


def save_user_config(config: dict[str, Any]) -> Path:
    """Save user-level lightcone-cli configuration."""
    config_path = get_config_path()
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    return config_path


# ---------------------------------------------------------------------------
# Cluster cache — stores raw scheduler limit data used by the runner for
# option validation.  Never surfaced to the agent.
# ---------------------------------------------------------------------------


def load_cluster_cache(target_name: str) -> Any:
    """Load cached ``ClusterInfo`` for a target, or ``None`` if absent."""
    from lightcone.engine.slurm_info import cluster_info_from_dict

    cache_path = get_cache_dir() / f"{target_name}.cluster.yaml"
    if not cache_path.exists():
        return None
    with open(cache_path) as f:
        data = yaml.safe_load(f)
    if not data:
        return None
    return cluster_info_from_dict(data)


def save_cluster_cache(target_name: str, info: Any) -> Path:
    """Write ``ClusterInfo`` to the cluster cache directory."""
    from lightcone.engine.slurm_info import cluster_info_to_dict

    cache_path = get_cache_dir() / f"{target_name}.cluster.yaml"
    data = cluster_info_to_dict(info)
    with open(cache_path, "w") as f:
        f.write("# AUTO-GENERATED by `lc target refresh`. Do not edit.\n")
        yaml.dump(data, f, default_flow_style=False, sort_keys=False)
    return cache_path


def is_cache_stale(target_name: str, max_age_days: int = 30) -> bool:
    """Return ``True`` if the cache is missing or older than *max_age_days*."""
    cache_path = get_cache_dir() / f"{target_name}.cluster.yaml"
    if not cache_path.exists():
        return True
    with open(cache_path) as f:
        data = yaml.safe_load(f)
    if not data or not data.get("timestamp"):
        return True
    try:
        ts = datetime.fromisoformat(data["timestamp"])
        return (datetime.now(UTC) - ts).days > max_age_days
    except (ValueError, TypeError):
        return True


def refresh_cluster_cache(target_name: str) -> Any:
    """Re-query the scheduler and rewrite the cache for *target_name*."""
    from lightcone.engine.slurm_info import discover_cluster

    info = discover_cluster()
    save_cluster_cache(target_name, info)
    return info


# ---------------------------------------------------------------------------
# Option helpers
# ---------------------------------------------------------------------------


def get_options(config: dict[str, Any]) -> dict[str, Any]:
    """Return the ``options`` mapping for a target (empty dict if absent)."""
    return config.get("options") or {}


def get_option_default(config: dict[str, Any], axis: str) -> Any:
    """Return the configured default for *axis*, or ``None``."""
    return (get_options(config).get(axis) or {}).get("default")


def get_option_choices(config: dict[str, Any], axis: str) -> dict[str, str]:
    """Return ``{value: guidance}`` for *axis*.  Accepts list form as well."""
    raw = (get_options(config).get(axis) or {}).get("choices") or {}
    if isinstance(raw, list):
        return {str(v): "" for v in raw}
    return {str(k): (v or "") for k, v in raw.items()}


def get_option_guidance(config: dict[str, Any], axis: str) -> str:
    """Return the overall guidance string for *axis*, if any."""
    return (get_options(config).get(axis) or {}).get("guidance") or ""


# ---------------------------------------------------------------------------
# Cache-key resolver — maps a user-facing (qos, constraint) pair to the
# sacctmgr record name used for limit lookup in the cluster cache.
# ---------------------------------------------------------------------------


def resolve_cache_key(
    qos: str,
    constraint: str | None,
    cache_qos_keys: Any,
    overrides: dict[str, str] | None = None,
) -> str:
    """Map ``(qos, constraint)`` to a scheduler cache record name.

    Lookup order:

    1. explicit ``cache_key_overrides`` entry (``{qos}/{constraint}`` or
       ``{qos}``);
    2. the convention ``{constraint}_{qos}`` when present in the cache
       (``gpu_debug`` on Perlmutter);
    3. ``{qos}`` verbatim.
    """
    if overrides:
        if constraint:
            key = f"{qos}/{constraint}"
            if key in overrides:
                return overrides[key]
        if qos in overrides:
            return overrides[qos]
    if constraint:
        prefixed = f"{constraint}_{qos}"
        if prefixed in cache_qos_keys:
            return prefixed
    return qos


def get_cache_key_overrides(config: dict[str, Any]) -> dict[str, str]:
    """Return the target's ``cache_key_overrides`` map (empty dict if none)."""
    raw = config.get("cache_key_overrides") or {}
    if not isinstance(raw, dict):
        return {}
    return {str(k): str(v) for k, v in raw.items()}


# ---------------------------------------------------------------------------
# Run-config resolution
# ---------------------------------------------------------------------------


def resolve_run_config(
    target_config: dict[str, Any],
    cli_overrides: dict[str, Any],
) -> dict[str, Any]:
    """Merge CLI overrides with option defaults.

    Resolution order per axis: ``cli_override > option default > None``.
    Validates ``qos`` and ``constraint`` against the target's declared
    choices.  For non-scheduler backends, warns on scheduler-only
    overrides and returns an empty dict.
    """
    backend = target_config.get("backend", "local")
    if backend != "slurm":
        stray = _SCHEDULER_AXES & set(cli_overrides)
        for axis in sorted(stray):
            logger.warning(
                "--%s is ignored for %s backend.", axis, backend,
            )
        return {}

    result: dict[str, Any] = {}
    for axis in OPTION_AXES:
        val = cli_overrides.get(axis)
        if val is None:
            val = get_option_default(target_config, axis)
        if val is not None:
            result[axis] = val

    # Validate qos / constraint against declared choices.
    for axis in ("qos", "constraint"):
        choices = get_option_choices(target_config, axis)
        chosen = result.get(axis)
        if choices and chosen and chosen not in choices:
            raise ValueError(
                f"'{chosen}' is not a valid {axis} for this target. "
                f"Choices: {sorted(choices)}"
            )

    return result
